~title[about]
~template[template.html]
~replace[<!--BODY-GOES-HERE-->]

h1["identify yourself, (REDACTED)"]
p[yo! i'm mason. i do dumb things, write nasty code, and hang out on discord. i wish the internet wasn't a corporate driven shithole so i pretend it isn't.]
h1[interests]
ul[<li>language dev</li><li>osdev</li><li>*nixes (except for linux, it's boring)</li><li>esolangs and old langs</li>]
h1[contact]
p[i exist in multiple places.]
h3[discord]
pre[sunny cark#7763]
h3[matrix]
pre[@snwy_:matrix.org]
h3[email]
pre[mason@snwy.me]